f=open("src/components/unira/MapView.tsx","w")
f.write("use client;\n")
f.write("\n")
f.write('import { useEffect, useRef } from \'react\';\n')
f.write('import L from \'leaflet\';\n')
f.write('import \'leaflet/dist/leaflet.css\';\n')
f.write("\n")
f.write('delete (L.Icon.Default.prototype as any)._getIconUrl;\n')
f.write('L.Icon.Default.mergeOptions({\n')
f.write('  iconRetinaUrl: \'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png\',\n')
f.write('  iconUrl: \'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png\',\n')
f.write('  shadowUrl: \'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png\',\n')
f.write('});\n')
f.write("\n")
f.write('interface MapViewProps {\n')
f.write('  origin: { lat: number; lng: number; name: string } | null;\n')
f.write('  destination: { lat: number; lng: number; name: string } | null;\n')
f.write('}\n')
f.write("\n")
f.write('export default function MapView({ origin, destination }: MapViewProps) {\n')
f.write('  const containerRef = useRef<HTMLDivElement>(null);\n')
f.write('  const mapRef = useRef<L.Map | null>(null);\n')
f.write('  const layerRef = useRef<L.LayerGroup | null>(null);\n')
f.write("\n")
f.write('  useEffect(() => {\n')
f.write('    if (!containerRef.current || mapRef.current) return;\n')
f.write('    const map = L.map(containerRef.current, { zoomControl: false, attributionControl: false }).setView([-34.6037, -58.3816], 13);\n')
f.write("    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19 }).addTo(map);\n")
f.write('    layerRef.current = L.layerGroup().addTo(map);\n')
f.write('    mapRef.current = map;\n')
f.write('    const fixSize = () => { if (mapRef.current) mapRef.current.invalidateSize(); };\n')
f.write('    setTimeout(fixSize, 100); setTimeout(fixSize, 300); setTimeout(fixSize, 600);\n')
f.write('    window.addEventListener(\'resize\', fixSize);\n')
f.write('    return () => { window.removeEventListener(\'resize\', fixSize); map.remove(); mapRef.current = null; layerRef.current = null; };\n')
f.write('  }, []);\n')
f.write("\n")
f.write('  useEffect(() => {\n')
f.write('    const map = mapRef.current; const layer = layerRef.current; if (!map || !layer) return;\n')
f.write('    layer.clearLayers(); const bounds: L.LatLngBounds = L.latLngBounds([]);\n')
f.write('    if (origin) { const m = L.circleMarker([origin.lat, origin.lng], { radius: 8, fillColor: \'#22C55E\', fillOpacity: 1, color: \'#fff\', weight: 3 }); m.addTo(layer); if (origin.name) m.bindTooltip(origin.name, { direction: \'top\', offset: [0, -10], className: \'unira-tooltip\' }); bounds.extend([origin.lat, origin.lng]); }\n')
f.write('    if (destination) { const m = L.circleMarker([destination.lat, destination.lng], { radius: 8, fillColor: \'#EF4444\', fillOpacity: 1, color: \'#fff\', weight: 3 }); m.addTo(layer); if (destination.name) m.bindTooltip(destination.name, { direction: \'top\', offset: [0, -10], className: \'unira-tooltip\' }); bounds.extend([destination.lat, destination.lng]); }\n')
f.write('    if (origin && destination) { L.polyline([[origin.lat, origin.lng], [destination.lat, destination.lng]], { color: \'#0EA5A0\', weight: 4, opacity: 0.8, dashArray: \'10, 14\' }).addTo(layer); if (bounds.isValid()) map.fitBounds(bounds, { padding: [60, 60], maxZoom: 16 }); } else if (origin) { map.setView([origin.lat, origin.lng], 14); } else { map.setView([-34.6037, -58.3816], 13); }\n')
f.write('  }, [origin, destination]);\n')
f.write("\n")
f.write('  return (\n')
f.write("    <div className=\"w-full h-full relative\">\n")
f.write("      <div ref={containerRef} className=\"w-full h-full rounded-2xl\" style={{ zIndex: 0 }} />\n")
f.write("      <style>{`.unira-tooltip{background:#1F2937!important;color:#F9FAFB!important;border:none!important;border-radius:8px!important;padding:4px 10px!important;font-size:12px!important;font-weight:600!important;box-shadow:0 2px 8px rgba(0,0,0,0.15)!important}.unira-tooltip::before{border-top-color:#1F2937!important}.leaflet-control-attribution{display:none!important}.leaflet-control-zoom{display:none!important}`}</style>\n")
f.write("    </div>\n")
f.write("  );\n")
f.write("}\n")
f.close()
